// bluebell-frontend/src/components/CreatePost.tsx
import React, { useEffect, useState } from 'react';
import { Form, Input, Button, Select, message, Space } from 'antd';
import { Community } from '../types';
import { postApi, communityApi } from '../services/api';

const { TextArea } = Input;

interface PostFormData {
  title: string;
  content: string;
  community_id: number;
}

const CreatePost: React.FC<{ onSuccess?: () => void }> = ({ onSuccess }) => {
  const [form] = Form.useForm<PostFormData>();
  const [communities, setCommunities] = useState<Community[]>([]);
  const [loading, setLoading] = useState(false);
  const [fetchingCommunities, setFetchingCommunities] = useState(false);

  useEffect(() => {
    const fetchCommunities = async () => {
      try {
        setFetchingCommunities(true);
        const response = await communityApi.getCommunityList();
        if (response.code === 0) {
          setCommunities(response.data);
        } else {
          message.error(response.message || '获取社区列表失败');
        }
      } catch (error) {
        console.error('获取社区列表失败:', error);
        message.error('获取社区列表失败，请稍后重试');
      } finally {
        setFetchingCommunities(false);
      }
    };
    fetchCommunities();
  }, []);

  const handleSubmit = async (values: PostFormData) => {
    try {
      setLoading(true);
      const response = await postApi.createPost(values);
      if (response.code === 0) {
        message.success('发帖成功！');
        form.resetFields();
        onSuccess?.();
      } else {
        message.error(response.message || '发帖失败');
      }
    } catch (error) {
      console.error('发帖失败:', error);
      message.error('发帖失败，请稍后重试');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Form
      form={form}
      layout="vertical"
      onFinish={handleSubmit}
      style={{ maxWidth: 800, margin: '0 auto', padding: '24px' }}
    >
      <Form.Item
        name="title"
        label="标题"
        rules={[
          { required: true, message: '请输入标题' },
          { max: 100, message: '标题最多100个字符' }
        ]}
      >
        <Input placeholder="请输入帖子标题" />
      </Form.Item>

      <Form.Item
        name="community_id"
        label="选择社区"
        rules={[{ required: true, message: '请选择社区' }]}
      >
        <Select
          placeholder="请选择发帖社区"
          loading={fetchingCommunities}
          disabled={fetchingCommunities}
        >
          {communities.map((community) => (
            <Select.Option key={community.id} value={community.id}>
              {community.name}
            </Select.Option>
          ))}
        </Select>
      </Form.Item>

      <Form.Item
        name="content"
        label="内容"
        rules={[
          { required: true, message: '请输入内容' },
          { max: 5000, message: '内容最多5000个字符' }
        ]}
      >
        <TextArea
          rows={6}
          placeholder="请输入帖子内容"
          showCount
          maxLength={5000}
        />
      </Form.Item>

      <Form.Item>
        <Space>
          <Button type="primary" htmlType="submit" loading={loading}>
            发布帖子
          </Button>
          <Button onClick={() => form.resetFields()}>重置</Button>
        </Space>
      </Form.Item>
    </Form>
  );
};

export default CreatePost;

// bluebell-frontend/src/views/CreatePost.vue
<template>
  <div class="max-w-4xl mx-auto">
    <div class="bg-white rounded-lg shadow">
      <div class="p-6">
        <h1 class="text-2xl font-bold mb-6">发布新帖子</h1>
        <form @submit.prevent="handleSubmit">
          <div class="space-y-6">
            <!-- 社区选择 -->
            <div>
              <label for="community" class="block text-sm font-medium text-gray-700">
                选择社区
              </label>
              <select
                id="community"
                v-model="form.community_id"
                required
                class="mt-1 input"
              >
                <option value="" disabled>请选择社区</option>
                <option
                  v-for="community in communities"
                  :key="community.id"
                  :value="community.id"
                >
                  {{ community.name }}
                </option>
              </select>
            </div>

            <!-- 标题 -->
            <div>
              <label for="title" class="block text-sm font-medium text-gray-700">
                标题
              </label>
              <input
                id="title"
                v-model="form.title"
                type="text"
                required
                class="mt-1 input"
                placeholder="请输入标题"
              >
            </div>

            <!-- 内容 -->
            <div>
              <label for="content" class="block text-sm font-medium text-gray-700">
                内容
              </label>
              <textarea
                id="content"
                v-model="form.content"
                rows="10"
                required
                class="mt-1 textarea"
                placeholder="请输入内容"
              ></textarea>
            </div>

            <!-- 提交按钮 -->
            <div class="flex justify-end">
              <button
                type="submit"
                class="btn btn-primary"
                :disabled="submitting"
              >
                <span v-if="submitting" class="flex items-center">
                  <span class="animate-spin h-4 w-4 mr-2 border-b-2 border-white rounded-full"></span>
                  发布中...
                </span>
                <span v-else>发布</span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import type { Community } from '@/types'
import { getCommunityList } from '@/api/community'
import { createPost } from '@/api/post'

const router = useRouter()
const route = useRoute()

const submitting = ref(false)
const communities = ref<Community[]>([])
const form = ref({
  community_id: route.query.community_id ? Number(route.query.community_id) : '',
  title: '',
  content: ''
})

const loadCommunities = async () => {
  try {
    communities.value = await getCommunityList()
  } catch (error) {
    console.error('Failed to load communities:', error)
  }
}

const handleSubmit = async () => {
  try {
    submitting.value = true
    const post = await createPost(form.value)
    router.push({
      name: 'post-detail',
      params: { id: post.id }
    })
  } catch (error: any) {
    alert(error.message || '发布失败')
  } finally {
    submitting.value = false
  }
}

onMounted(() => {
  loadCommunities()
})
</script>
